apiVersion: v1
kind: Service
metadata:
  name: fast-vector
  labels:
    app.kubernetes.io/name: fast-vector
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fast-vector
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
